export const PALETTES = {
  ocean: {
    '--ms-accent':               '#2563eb',
    '--ms-accent-dark':          '#1d4ed8',
    '--ms-accent-pale':          '#eff6ff',
    '--ms-accent-border':        '#bfdbfe',
    '--ms-accent-dim':           'rgba(37,99,235,0.18)',
    '--ms-accent-glow':          'rgba(37,99,235,0.35)',
    '--ms-accent-light':         '#60a5fa',
    '--ms-sidebar':              '#0f172a',
    '--ms-sidebar-gradient-mid': '#1e3a8a',
    '--ms-sidebar-gradient-end': '#1d4ed8',
  },
  foret: {
    '--ms-accent':               '#059669',
    '--ms-accent-dark':          '#047857',
    '--ms-accent-pale':          '#f0fdf4',
    '--ms-accent-border':        '#a7f3d0',
    '--ms-accent-dim':           'rgba(5,150,105,0.15)',
    '--ms-accent-glow':          'rgba(5,150,105,0.3)',
    '--ms-accent-light':         '#34d399',
    '--ms-sidebar':              '#052e16',
    '--ms-sidebar-gradient-mid': '#065f46',
    '--ms-sidebar-gradient-end': '#047857',
  },
  crepuscule: {
    '--ms-accent':               '#7c3aed',
    '--ms-accent-dark':          '#6d28d9',
    '--ms-accent-pale':          '#f5f3ff',
    '--ms-accent-border':        '#ddd6fe',
    '--ms-accent-dim':           'rgba(124,58,237,0.15)',
    '--ms-accent-glow':          'rgba(124,58,237,0.35)',
    '--ms-accent-light':         '#a78bfa',
    '--ms-sidebar':              '#1e1b4b',
    '--ms-sidebar-gradient-mid': '#3730a3',
    '--ms-sidebar-gradient-end': '#6d28d9',
  },
  ardoise: {
    '--ms-accent':               '#475569',
    '--ms-accent-dark':          '#334155',
    '--ms-accent-pale':          '#f8fafc',
    '--ms-accent-border':        '#cbd5e1',
    '--ms-accent-dim':           'rgba(71,85,105,0.12)',
    '--ms-accent-glow':          'rgba(71,85,105,0.25)',
    '--ms-accent-light':         '#94a3b8',
    '--ms-sidebar':              '#020617',
    '--ms-sidebar-gradient-mid': '#1e293b',
    '--ms-sidebar-gradient-end': '#334155',
  },
} as const;

export type PaletteKey = keyof typeof PALETTES;
